import type { Task, Workflow, ComplianceInsight, ChartOfAccounts, FinancialPeriod } from "@/types"

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 1,
    name: "Registro Automático de Facturas de Venta",
    category: "revenue",
    description: "Automatiza el registro contable de facturas de venta con validación de cuentas por cobrar",
    active: true,
    lastRun: "hace 5 minutos",
    accuracy: 99.2,
    complianceLevel: "high",
    auditRequired: true,
  },
  {
    id: 2,
    name: "Conciliación Bancaria Automática",
    category: "banking",
    description: "Concilia automáticamente los movimientos bancarios con los registros contables",
    active: true,
    lastRun: "hace 2 horas",
    accuracy: 97.8,
    complianceLevel: "high",
    auditRequired: true,
  },
  {
    id: 3,
    name: "Cálculo de Depreciación de Activos Fijos",
    category: "assets",
    description: "Calcula y registra automáticamente la depreciación mensual de activos fijos",
    active: false,
    lastRun: "hace 1 semana",
    accuracy: 100.0,
    complianceLevel: "high",
    auditRequired: true,
  },
  {
    id: 4,
    name: "Procesamiento de Gastos por Pagar",
    category: "expenses",
    description: "Registra automáticamente las cuentas por pagar basado en facturas de proveedores",
    active: true,
    lastRun: "hace 30 minutos",
    accuracy: 98.5,
    complianceLevel: "medium",
    auditRequired: false,
  },
  {
    id: 5,
    name: "Generación de Asientos de Cierre Mensual",
    category: "closing",
    description: "Genera automáticamente los asientos de ajuste y cierre del período contable",
    active: false,
    lastRun: "hace 1 mes",
    accuracy: 99.8,
    complianceLevel: "high",
    auditRequired: true,
  },
]

export const MOCK_COMPLIANCE_INSIGHTS: ComplianceInsight[] = [
  {
    id: 1,
    type: "tax_compliance",
    title: "Declaración de IVA Pendiente",
    description: "La declaración de IVA del mes de mayo debe presentarse antes del 15 de junio",
    dataSource: "Sistema Fiscal",
    confidence: 100,
    impact: "high",
    recommendation: "Revisar y presentar la declaración de IVA inmediatamente",
    regulatoryFramework: "Código Tributario Nacional",
    dueDate: "2024-06-15",
    details: {
      period: "Mayo 2024",
      amount: "$15,450.00",
      status: "Pendiente",
    },
  },
  {
    id: 2,
    type: "audit_finding",
    title: "Discrepancia en Inventario",
    description: "Se detectó una diferencia del 2.3% entre el inventario físico y contable",
    dataSource: "Módulo de Inventarios",
    confidence: 95,
    impact: "medium",
    recommendation: "Realizar ajuste de inventario y revisar procedimientos de control",
    regulatoryFramework: "NIIF para PYMES",
    details: {
      variance: "2.3%",
      amount: "$8,750.00",
      lastCount: "2024-05-30",
    },
  },
  {
    id: 3,
    type: "regulatory_alert",
    title: "Cambio en Normativa Contable",
    description: "Nueva normativa NIIF 16 sobre arrendamientos entra en vigor el próximo trimestre",
    dataSource: "Consejo de Normas Contables",
    confidence: 100,
    impact: "high",
    recommendation: "Capacitar al equipo contable y actualizar políticas de arrendamiento",
    regulatoryFramework: "NIIF 16",
    dueDate: "2024-07-01",
    details: {
      effectiveDate: "2024-07-01",
      impact: "Arrendamientos operativos",
      training: "Requerida",
    },
  },
  {
    id: 4,
    type: "financial_anomaly",
    title: "Variación Inusual en Gastos Operativos",
    description: "Los gastos operativos aumentaron 15% respecto al mes anterior sin justificación aparente",
    dataSource: "Estados Financieros",
    confidence: 87,
    impact: "medium",
    recommendation: "Analizar detalle de gastos y solicitar justificación a los departamentos",
    regulatoryFramework: "Control Interno",
    details: {
      variance: "15%",
      amount: "$12,300.00",
      period: "Mayo 2024",
    },
  },
]

export const MOCK_CHART_OF_ACCOUNTS: ChartOfAccounts[] = [
  {
    id: "1",
    accountCode: "1110",
    accountName: "Caja",
    accountType: "asset",
    isActive: true,
    balance: 25000.0,
    normalBalance: "debit",
  },
  {
    id: "2",
    accountCode: "1120",
    accountName: "Bancos",
    accountType: "asset",
    isActive: true,
    balance: 150000.0,
    normalBalance: "debit",
  },
  {
    id: "3",
    accountCode: "1210",
    accountName: "Cuentas por Cobrar",
    accountType: "asset",
    isActive: true,
    balance: 85000.0,
    normalBalance: "debit",
  },
  {
    id: "4",
    accountCode: "2110",
    accountName: "Cuentas por Pagar",
    accountType: "liability",
    isActive: true,
    balance: 45000.0,
    normalBalance: "credit",
  },
  {
    id: "5",
    accountCode: "3110",
    accountName: "Capital Social",
    accountType: "equity",
    isActive: true,
    balance: 200000.0,
    normalBalance: "credit",
  },
  {
    id: "6",
    accountCode: "4110",
    accountName: "Ingresos por Ventas",
    accountType: "revenue",
    isActive: true,
    balance: 350000.0,
    normalBalance: "credit",
  },
  {
    id: "7",
    accountCode: "5110",
    accountName: "Costo de Ventas",
    accountType: "expense",
    isActive: true,
    balance: 180000.0,
    normalBalance: "debit",
  },
]

export const MOCK_FINANCIAL_PERIODS: FinancialPeriod[] = [
  {
    id: "1",
    name: "Enero 2024",
    startDate: "2024-01-01",
    endDate: "2024-01-31",
    status: "closed",
    fiscalYear: "2024",
  },
  {
    id: "2",
    name: "Febrero 2024",
    startDate: "2024-02-01",
    endDate: "2024-02-29",
    status: "closed",
    fiscalYear: "2024",
  },
  {
    id: "3",
    name: "Marzo 2024",
    startDate: "2024-03-01",
    endDate: "2024-03-31",
    status: "closed",
    fiscalYear: "2024",
  },
  {
    id: "4",
    name: "Abril 2024",
    startDate: "2024-04-01",
    endDate: "2024-04-30",
    status: "closed",
    fiscalYear: "2024",
  },
  {
    id: "5",
    name: "Mayo 2024",
    startDate: "2024-05-01",
    endDate: "2024-05-31",
    status: "closed",
    fiscalYear: "2024",
  },
  {
    id: "6",
    name: "Junio 2024",
    startDate: "2024-06-01",
    endDate: "2024-06-30",
    status: "open",
    fiscalYear: "2024",
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 1,
    description: "Validación automática de asientos contables - Lote 045",
    date: "2024-06-24 14:30",
    result:
      "Se validaron exitosamente 43 asientos contables. 2 requieren revisión manual debido a desbalances menores.",
    reasoning:
      "Se aplicó validación de partida doble y verificación de cuentas contables. Los asientos con desbalances menores a $0.50 fueron marcados para revisión manual según políticas de control interno.",
    status: "pending",
    confidence: 96,
    category: "validation",
    priority: "medium",
  },
  {
    id: 2,
    description: "Conciliación bancaria automática - Cuenta 1120",
    date: "2024-06-24 12:15",
    result: "Conciliación completada con 98.5% de coincidencias. Se identificaron 3 partidas en tránsito.",
    reasoning:
      "Se compararon los movimientos bancarios con el libro auxiliar de bancos. Las partidas en tránsito corresponden a cheques emitidos pero no cobrados según el estado de cuenta.",
    status: "approved",
    confidence: 98,
    category: "reconciliation",
    priority: "high",
  },
  {
    id: 3,
    description: "Detección de anomalías en gastos operativos",
    date: "2024-06-24 10:45",
    result: "Se detectaron 3 transacciones con variaciones significativas que requieren autorización gerencial.",
    reasoning:
      "El algoritmo de detección identificó gastos que exceden el 20% del promedio histórico mensual, activando el protocolo de revisión gerencial según políticas de control interno.",
    status: "rejected",
    confidence: 89,
    category: "anomaly_detection",
    priority: "high",
  },
  {
    id: 4,
    description: "Cálculo automático de depreciación - Activos fijos",
    date: "2024-06-24 09:00",
    result: "Depreciación calculada para 156 activos fijos utilizando método línea recta. Total: $12,450.75",
    reasoning:
      "Se aplicó el método de depreciación línea recta según las políticas contables establecidas. Los cálculos incluyen verificación de vida útil y valor residual de cada activo.",
    status: "approved",
    confidence: 100,
    category: "depreciation",
    priority: "medium",
  },
  {
    id: 5,
    description: "Validación de cumplimiento fiscal - IVA Mayo 2024",
    date: "2024-06-24 08:15",
    result: "Revisión de cumplimiento completada. Se identificaron 2 facturas sin registro de IVA.",
    reasoning:
      "Se verificó el cumplimiento de obligaciones fiscales comparando las facturas emitidas con los registros de IVA. Las facturas faltantes fueron identificadas para corrección.",
    status: "pending",
    confidence: 94,
    category: "tax_compliance",
    priority: "high",
  },
]
